/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.barbearia.View;

import com.barbearia.Controller.LoginController;
import com.barbearia.Model.DAO.Refatorar.Banco;

import javax.swing.*;

/**
 *
 * @author JOÃO
 */
public class Login extends javax.swing.JFrame {

    private final LoginController controller;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        controller = new LoginController(this);
        Banco.inicia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        textUsuarioInput = new javax.swing.JTextArea();
        textSenha = new javax.swing.JPasswordField();
        jLabel4_usuario = new javax.swing.JLabel();
        jLabel5_senha = new javax.swing.JLabel();
        jLabel2_login = new javax.swing.JLabel();
        jLabel3_painelLogin = new javax.swing.JLabel();
        jLabel1_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 460, 330, -1));

        textUsuarioInput.setColumns(20);
        textUsuarioInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textUsuarioInput.setRows(5);
        getContentPane().add(textUsuarioInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 330, 40));

        textSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(textSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 330, 40));

        jLabel4_usuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4_usuario.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4_usuario.setText("Usuário");
        getContentPane().add(jLabel4_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 330, 40));

        jLabel5_senha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5_senha.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5_senha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5_senha.setText("Senha");
        getContentPane().add(jLabel5_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 330, 40));

        jLabel2_login.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2_login.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_login.setText("Login");
        getContentPane().add(jLabel2_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 330, 50));

        jLabel3_painelLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/painel2.png"))); // NOI18N
        getContentPane().add(jLabel3_painelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        jLabel1_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoDesenho.jpg"))); // NOI18N
        jLabel1_fundo.setText("Login");
        getContentPane().add(jLabel1_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 599, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextUsuarioActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    } 
    private void textSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSenhaActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.controller.entrarNoSistema();
        
                
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1_fundo;
    private javax.swing.JLabel jLabel2_login;
    private javax.swing.JLabel jLabel3_painelLogin;
    private javax.swing.JLabel jLabel4_usuario;
    private javax.swing.JLabel jLabel5_senha;
    private javax.swing.JPasswordField textSenha;
    private javax.swing.JTextArea textUsuarioInput;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @param mensagem
     */
    public void exibeMensagem(String mensagem){
        JOptionPane.showMessageDialog(null, mensagem);
    }

    public void setTextSenha(JPasswordField textSenha) {
        this.textSenha = textSenha;
    }

    public void setTextUsuarioInput(JTextArea textUsuarioInput) {
        this.textUsuarioInput = textUsuarioInput;
    }

    public JPasswordField getTextSenha() {
        return textSenha;
    }

    public JTextArea getTextUsuarioInput() {
        return textUsuarioInput;
    }

    public JLabel getjLabel4_usuario() {
        return jLabel4_usuario;
    }

    public JLabel getjLabel5_senha() {
        return jLabel5_senha;
    }
    
    
}
